---

# Targeting specific OSes or distributions:
#
#   - `ansible_system`               → Linux, BSD, ...
#   - `ansible_os_family`            → Debian, RedHat, ...
#   - `ansible_distribution`         → Debian, Ubuntu, RedHat, ...
#   - `ansible_distribution_release` → precise, wheezy, ...
#   - `ansible_pkg_mgr`              → apt, yum, ...

- name: Debian | Install Supervisord dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ supervisor_dependencies }}"
  when: ansible_os_family == 'Debian'
  tags:
    - deps
    - supervisor
    - supervisord

- name: Darwin | Install Supervisord dependencies
  become: yes
  easy_install:
    name: "{{ item }}"
    state: present
  with_items: "{{ supervisor_dependencies }}"
  when: ansible_os_family == 'Darwin'
  tags:
    - deps
    - supervisor
    - supervisord

# use apt since service installed w/pip doesn't start on Ubuntu 16.04
- name: Install Supervisord (specific version)
  become: yes
  apt:
    name: supervisor={{supervisor_version}}
    state: present
  when: "supervisor_version != 'latest' and supervisor_version != 'present'"
  tags:
    - deps
    - supervisor
    - supervisord

- name: Install Supervisord (latest version or just present)
  become: yes
  apt:
    name: supervisor
    state: present
  when: "supervisor_version == 'latest' or supervisor_version == 'present'"
  tags:
    - deps
    - supervisor
    - supervisord

    